server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wiki
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:


  devtools:
    restart:
      enabled: true


mybatis:
  mapper-locations: maperr/**.xml
  type-aliases-package: com.kfm.wiki.model
  configuration:
    use-actual-param-name: true


